### ISSUE TITLE
Deep searching doesn't work in s3 buckets, when inside a sub directory of the bucket

### ISSUE THREAD

**Issue by cs96and** [theripper93/fuzzy-foundry#10]
Dig Down Version: 1.8.1
Foundry Version: 10.291

If you enable s3 mode, the deep searching works from the root of the s3 bucket.  If you go into a sub directory of the bucket, then the deep searching no longer works....

![image](https://user-images.githubusercontent.com/898086/209365736-c3848de7-6eb8-46a3-ac0f-fad015ed46b6.png)

![image](https://user-images.githubusercontent.com/898086/209365822-8d96f4f2-699d-43fd-bc1c-2a5f9fd7d713.png)

**Comment by theripper93** [comment]
Unfortunately I have no s3 buckets to test with, that implementation was done blind, would it be possible for you to check were it goes wrong and possibly send a PR?

**Comment by cs96and** [comment]
Yeah I sort of worked out what the problem was.  I'll see if I can fix it and submit a PR
