### ISSUE TITLE
Deep file search: character limit option does not work

### ISSUE THREAD

**Issue by Lifthraser** [theripper93/fuzzy-foundry#15]
The option to set the minimum number of characters required to trigger the deep file search does not work.
If changed to less than 4, does not deep search until it reach 4, and if changed to more than 4, still deep search starting at 4 characters.
Tried rebuilding cache and reloading. didnt work either.
Tested with foundry V10 build 291 with latest pathfinder2 and dungeon world systems with the same results.

**Comment by theripper93** [comment]
Fixed
