### ISSUE TITLE
Noscan not working

### ISSUE THREAD

**Issue by cah-98** [theripper93/fuzzy-foundry#17]
Hi, i tried using the noscan function by putting a file named .noscan in a directory and rebuilding the file cache. I have tried multiple times with different folders and reloaded foundry multiple times as well. Whatever i do the files in the .noscan folder still get detected by the module and i get no console logs about .noscan either.

**Comment by theripper93** [comment]
@cs96and

**Comment by cs96and** [comment]
It seems `FilePicker.browse()` ignores hidden files, so it doesn't find the .noscan files...
https://github.com/foundryvtt/foundryvtt/issues/4024

Though it does seem to see those files in s3 buckets.

I'll change it so that it has to find `noscan.txt` instead.

**Comment by cs96and** [comment]
#18
