### ISSUE TITLE
Unable to get Deep File Search to work

### ISSUE THREAD

**Issue by MNBlockhead** [theripper93/fuzzy-foundry#2]
I've installed the module, selected the Deep File Search option in the module's settings and let the cache build overnight, but I do not see any different behavior when searching in the file picker. Maybe I'm misunderstanding what they mean by file picker. I'm understanding that to mean that when click on the "Use Image from Foundry Server" button and Image or Video Browser window comes up, that I should be able to type text in the search bar and would expect results from subfolders as well as items in the currently open folder. But that doesn't happen and I see no other option to allow it.

There are no screen shots in any of the Dig Down documentation on Git Hub, FoundryVTT-Hub, or the Foundry VTT packages/modules page that gives a screen shot of the "Deep File Search" in action. So I don't know if something went wrong in the installation or the building of my cache.

**Comment by theripper93** [comment]
Just to make sure, you need at least 4 letters in the search for dig down to go deep- can you verify that you tested search terms at least this long?

**Comment by theripper93** [comment]
no follow up - closed
