### ISSUE TITLE
File cache not saved, gets rebuild on every load

### ISSUE THREAD

**Issue by marcstraube** [theripper93/fuzzy-foundry#3]
Foundry Version: 9.242
Enabled Modules: Dig Down 1.4, libWrapper 1.11.2.0

When Deep File Search is enabled, the module wants to build the file cache on every load of the game.

On load, the message "Dig Down - Building File cache, please don't refresh, this can take some time..." is shown.
The Console shows a 404 error for https://my.domain.tld/DigDownCache.json and after a while the debug notice "Saved XXX files to cache" appears.

After a reload, the same process starts again.

Even when the "Rebuild File Cache" button is used, the problem persists.

**Comment by theripper93** [comment]
mmm, is the file there after the cache is built? might be some kind of server permission issue because this issue was never reported before

**Comment by marcstraube** [comment]
Thanks! Seems I got some ownership or permission mode wrong during the update to Foundry 9.
chown and chmod did the job.

**Comment by Gensokian** [comment]
Sorry to re-open this older issue.
Where does the filecache build to? I'm using Felddys Docker and for me the cache gets cleared on reload too, but since I don't have the luxury of chaniging the permissions directly, I'd need to change the permissions in the startup script

**Comment by theripper93** [comment]
Direcly in the foundry Data folder (where your "modules" folder is)
