### ISSUE TITLE
Cannot get DigDownCache.json

### ISSUE THREAD

**Issue by Gensokian** [theripper93/fuzzy-foundry#6]
I got a bit of an issue with my setup, since it's running behind a reverse proxy the URL for my game is not going by the default URL (Like DigDown is trying to anticipate).

DigDown pushes the URL to https://dnd.myurl.com/DigDownCache.json which is okay for the usual foundry setup.
But my setup is behind a reverse proxy, so the URL needs to be https://dnd.myurl.com/FOUNDRY_ROUTE_PREFIX/DigDownCache.json

**Comment by theripper93** [comment]
I have no clue how to solve that issue, ether you modify the module code or, if you have network knowledge and want to push a fix for reverse proxy feel free to

**Comment by Gensokian** [comment]
This should do the do. it now checks if there are any subdirectories present.

**Comment by theripper93** [comment]
merged
