### ISSUE TITLE
Documents in the second and third level subfolders are not showing up

### ISSUE THREAD

**Issue by superseva** [theripper93/fuzzy-foundry#8]
Took me a while to figure this out.
Documents in the second or third level subfolders are not found in search unless there is a match that happens in the upper folder structure. If the search finds something in the root or the first level subfolder then everything deeper is also found. Otherwise, if no match occurs in the root or the first level subfolder nothing in deeper folders is found (not even if you search only by name).

Foundry v10.287
Running Node in Chrome on Win 10

![steps-to-reproduce](https://user-images.githubusercontent.com/4093045/195689491-dee823a6-5ebb-4f22-9d52-d63d53763362.png)

**Comment by theripper93** [comment]
fixed
