### ISSUE TITLE
Conflit with the module "Compendium Folder"

### ISSUE THREAD

**Issue by CaosFR** [theripper93/fuzzy-foundry#9]
Hi,

Thanks for your greats module.
Your module is incompatible with "Compendium Folder" module. I can't use it with your module.

I have this warning when I open a compendium (with folder from the module) : 

![image](https://user-images.githubusercontent.com/37581932/197883746-425c9a92-4225-47c5-93c6-da265a90f3d2.png)
![image](https://user-images.githubusercontent.com/37581932/197883783-d27371aa-a81c-4a81-97ac-a381ea643c01.png)

**Comment by CaosFR** [comment]
The deep search work very random.

**Comment by CaosFR** [comment]
Sorry my post was incomplete, I have press 'enter' like a fool. The deep search work very random. Some time I have a fatal error, some time it's working.

"Compendium Folder" seems to work perfectely.

The error :
![image](https://user-images.githubusercontent.com/37581932/197885326-cbb2a9d0-fe88-442e-95bc-206a9f88f650.png)

**Comment by theripper93** [comment]
Please follow the repo instructions on reporting issues before we continue

**Comment by CaosFR** [comment]
**ALL OTHER MODULES DISABLED?** : False
**Module:** (name and version) : Dig Down v1.6.4
**Conflicting Module (if applicable)**:  Compendium Folders v2.5.5 (https://github.com/earlSt1/vtt-compendium-folders) 
**Foundry and System version**: eg. Foundry 10.288 DnD5e 2.0.3
**OS, Hosting, Browser (if applicable)**: Debian 11, Self, Chromium
**Short Description of bug**: The deep search work very random. Some time I have a fatal error, some time it's working.
**Simple steps to reproduce the bug**: Perform a deep search to see error or open a compendium to see warning.
**Screenshots and/or console errors**: Se post below

**Comment by theripper93** [comment]
Please disable all other modules and provide clear steps

**Comment by CaosFR** [comment]
@theripper93 All other other modules instead of compendium folder was enable. Without compendium folder I dont have any error.

Step by step : 
- Go to compendium tab, 
- Open a compendium with folder inside (compendium folder)
- See warning on screen and console

- Create a new actor, 
- Open it's prototype token and select a file
- Search "&x.webp" or "x.webp" (the deep search it's work must of time)
- See errror in console

**Comment by theripper93** [comment]
should be fixed

**Comment by CaosFR** [comment]
Thanks
